name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set environment variables
      run: |
        echo "ORG_NAME=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "CONTAINER_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push Docker image for ebs-recipe-app
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.ORG_NAME }}/ebs-recipe-app:${{ env.CONTAINER_VERSION }}
          ghcr.io/${{ env.ORG_NAME }}/ebs-recipe-app:latest